# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-lists.sh - DO NOT EDIT

adb pull /system/bin/btmacreader
adb pull /system/bin/glgps
adb pull /system/bin/sensors-config
adb pull /system/bin/tf_daemon
adb pull /system/etc/asound.conf
adb pull /system/etc/firmware/bcm4330.hcd
adb pull /system/etc/firmware/nvavp_os_00001000.bin
adb pull /system/etc/firmware/nvavp_os_0ff00000.bin
adb pull /system/etc/firmware/nvavp_os_e0000000.bin
adb pull /system/etc/firmware/nvavp_os_eff00000.bin
adb pull /system/etc/firmware/nvavp_vid_ucode_alt.bin
adb pull /system/etc/firmware/touch_fw.ekt
adb pull /system/etc/gps/gpsconfig.xml
adb pull /system/etc/nvcamera.conf
adb pull /system/etc/nvram.txt
adb pull /system/lib/egl/libEGL_tegra.so
adb pull /system/lib/egl/libGLESv1_CM_tegra.so
adb pull /system/lib/egl/libGLESv2_tegra.so
adb pull /system/lib/hw/camera.tegra3.so
adb pull /system/lib/hw/gps.tegra3.so
adb pull /system/lib/hw/gralloc.tegra3.so
adb pull /system/lib/hw/hwcomposer.tegra3.so
adb pull /system/lib/hw/keystore.grouper.so
adb pull /system/lib/hw/sensors.grouper.so
adb pull /system/lib/libardrv_dynamic.so
adb pull /system/lib/libcgdrv.so
adb pull /system/lib/libdrmdecrypt.so
adb pull /system/lib/libinvensense_hal.so
adb pull /system/lib/libmllite.so
adb pull /system/lib/libmplmpu.so
adb pull /system/lib/libnvapputil.so
adb pull /system/lib/libnvasfparserhal.so
adb pull /system/lib/libnvaviparserhal.so
adb pull /system/lib/libnvavp.so
adb pull /system/lib/libnvcamerahdr.so
adb pull /system/lib/libnvddk_2d.so
adb pull /system/lib/libnvddk_2d_v2.so
adb pull /system/lib/libnvdispmgr_d.so
adb pull /system/lib/libnvmm.so
adb pull /system/lib/libnvmmlite.so
adb pull /system/lib/libnvmmlite_audio.so
adb pull /system/lib/libnvmmlite_image.so
adb pull /system/lib/libnvmmlite_utils.so
adb pull /system/lib/libnvmmlite_video.so
adb pull /system/lib/libnvmm_audio.so
adb pull /system/lib/libnvmm_camera.so
adb pull /system/lib/libnvmm_contentpipe.so
adb pull /system/lib/libnvmm_image.so
adb pull /system/lib/libnvmm_manager.so
adb pull /system/lib/libnvmm_misc.so
adb pull /system/lib/libnvmm_parser.so
adb pull /system/lib/libnvmm_service.so
adb pull /system/lib/libnvmm_utils.so
adb pull /system/lib/libnvmm_video.so
adb pull /system/lib/libnvmm_writer.so
adb pull /system/lib/libnvodm_dtvtuner.so
adb pull /system/lib/libnvodm_hdmi.so
adb pull /system/lib/libnvodm_imager.so
adb pull /system/lib/libnvodm_misc.so
adb pull /system/lib/libnvodm_query.so
adb pull /system/lib/libnvomx.so
adb pull /system/lib/libnvomxilclient.so
adb pull /system/lib/libnvos.so
adb pull /system/lib/libnvparser.so
adb pull /system/lib/libnvrm.so
adb pull /system/lib/libnvrm_graphics.so
adb pull /system/lib/libnvsm.so
adb pull /system/lib/libnvtvmr.so
adb pull /system/lib/libnvwinsys.so
adb pull /system/lib/libnvwsi.so
adb pull /system/lib/libsensors.lightsensor.so
adb pull /system/lib/libstagefrighthw.so
adb pull /system/lib/libtf_crypto_sst.so
adb pull /system/vendor/firmware/libpn544_fw.so
adb pull /system/vendor/lib/drm/libdrmwvmplugin.so
adb pull /system/vendor/lib/libwvdrm_L1.so
adb pull /system/vendor/lib/libwvm.so
adb pull /system/vendor/lib/libWVStreamControlAPI_L1.so
